### ISSUE TITLE
bug: TOC 機能

### ISSUE THREAD

**Issue by next-shiyon** [next-shiyon/devlog#17]
以下の画像のように、h2, h3 タグがないのに TOC が生成されてしまう
コンテンツがなかったら TOC を描画しないようにするのが望ましい

<img width="1710" alt="image" src="https://github.com/next-shiyon/devlog/assets/138292822/7e395544-0374-4eb2-8f0d-b06321206e85">

**Comment by next-shiyon** [comment]
SP 画面の時に、以下のように処理したのでクローズ
```css
.table-of-contents {
      display: none;
}
```
